### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by plarrea** [j-em/react-authorize-net#1]
Is it possible to create subscriptions, cancel them and change the preferred payment method once is set using this library? Or is it only for one time payments?

**Comment by jeremy-hunter** [comment]
This library helps a React app exchange card number/code/exp for a nonce (token) via Accept.js. Once you have the nonce you can send that to authorize.net in place of traditional CC data - avoiding the CC data ever touching your server.

There is a callback for onSuccess which is where you would either store the nonce in state to be sent later or make a call to your backend server with the nonce +amount +  anything else you need to make a payment.

On the backend you would manage subscriptions using the official library:
https://github.com/AuthorizeNet/sdk-node
Subscription example is in this repo:
https://github.com/AuthorizeNet/sample-code-node

Hope this helps

**Comment by plarrea** [comment]
It helps, thank you so much!
