### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by nisargrthakkar** [j-em/react-authorize-net#10]
Facing the following issue while using react-authorize-net with next js 

`import _extends from '@babel/runtime/helpers/extends';`

Please check screenshot for more details

![Screenshot_2](https://user-images.githubusercontent.com/26029722/68936024-9c42e880-07bf-11ea-85a6-d86d9d79b618.png)

**Comment by nisargrthakkar** [comment]
I also try this issue https://github.com/j-em/react-authorize-net/issues/7

**Comment by j-em** [comment]
Anyone trying to integrate the lib with nextjs, have a look at this repo: https://github.com/j-em/react-authorize-net-nextjs

Feel free to open a new issue if you are still having issues with nextjs.
