### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module (possibly caused by Next.js?)

### ISSUE THREAD

**Issue by nkkollaw** [j-em/react-authorize-net#12]
I'm getting this error after I install the component.

I'm using CRA, and I'm not sure if this is caused by Next.js, since the example app works for me.

This is the log:

```
Module._compile
internal/modules/cjs/loader.js:892:18
Module._extensions..js
internal/modules/cjs/loader.js:973:10
Module.load
internal/modules/cjs/loader.js:812:32
Function.Module._load
internal/modules/cjs/loader.js:724:14
Module.require
internal/modules/cjs/loader.js:849:19
require
internal/modules/cjs/helpers.js:74:18
react-authorize-net
webpack:/external "react-authorize-net":1

> 1 | module.exports = require("react-authorize-net");


View compiled
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
```

**Comment by lleseg** [comment]
I have the exact same issue and I'm also using Next.js... It's not happening all the time so it is difficult to find a pattern or a cause.

Have you found a solution @nkkollaw?

**Comment by nkkollaw** [comment]
I haven't. I'm just calling the API directly
Too bad, but I guess not enough people use Next.js.

**Comment by lleseg** [comment]
I'm sorry @nkkollaw, I deleted my comment (though it seems you have the notification anyway) because I think this issue was solved in #7 and I'm still testing the solution. 

For now I haven't had the error again, maybe you can try that too?

**Comment by nkkollaw** [comment]
Gotcha, NP.

**Comment by tonymckendry** [comment]
I solved this in NextJS by using a dynamic import: 
`const Hosted = dynamic(() => import('react-authorize-net').then(p => p.AcceptHosted), { ssr: false })`

**Comment by j-em** [comment]
I have a repo here showing how to integrate the library with the latest version of nextjs (15 atm) https://github.com/j-em/react-authorize-net-nextjs

I'll close this for now, but feel free to open a new issue if you are still having problems making it work with nextjs.
