### ISSUE TITLE
Host iframeCommunicator.html file on GCP

### ISSUE THREAD

**Issue by j-em** [j-em/react-authorize-net#16]

**Comment by randyrollog** [comment]
@j-em Hey Jeremy, thanks for building this reactified version for Authorize.net! I am currently doing the same and this has made it a lot easier. 

I was wondering how you implemented the `IFrameCommunicator.html` page in your app. And how you referenced it in Authorize.net under the `hostedProfileIFrameCommunicatorUrl` parameter? Can't I just plug in that code in my index.html file and reference the homepage?

Thanks in advanced and look forward to hearing from you!

-Randy
