### ISSUE TITLE
cardData expects expDate to be an array

### ISSUE THREAD

**Issue by jeremy-hunter** [j-em/react-authorize-net#2]
Hi - thank you for this library, Accept.js is a pain to implement :)

In FormContainer submitHandler it expects expDate to be an array but since I have linked it to an input field my event.target.value is a string value. The original code sends a single digit month and year to auth.net which fails validation.

My workaround is below - is this something to be fixed or do I need to adjust how I'm handling my input?

```
submitHandler(): Promise<Accept.Response> {
    const authData = {
      apiLoginID: this.props.apiLoginId,
      clientKey: this.props.clientKey
    }
    const cardData = {
      cardCode: this.state.values.cardCode,
      cardNumber: this.state.values.cardNumber,
      month: **this.state.values.expDate.split("/")[0],**
      year: **this.state.values.expDate.split("/")[1]**
    }
```

**Comment by jgarib** [comment]
I found the same issue and came to the same fix before coming here to post and find you did the same.

The existing code only sends the submitted month value. The first digit of the month is the single digit for month, and the second digit for the month will be the second single digit (sent for year).

Also, the spaces need to be removed from the credit card number for it to match the length accepted by the API.

**Comment by j-em** [comment]
Thank you for taking the time to report this!

The code handling `this.state.values.expDate` like its an Array is definitely a bug.
#3 should be fixing this.

Don't hesitate to create another issue if there is anything else.
