### ISSUE TITLE
User authentication failed due to invalid authentication values.

### ISSUE THREAD

**Issue by edpaulsen** [j-em/react-authorize-net#33]
Using my sandbox creds, I am able to create transactions in my sandbox using other Authorize.net API Calls (API LIVE in Authorize.net Developer and the NODE Payment Transaction).  With this app with the default creds I get this error:

{code: "E_WC_10", text: "Please provide valid apiloginid."}
{code: "E_WC-18", text: :"Client key is required."}

When I swap out the creds with those that work elsewhere
//let clientKey = process.env.REACT_APP_AUTHORIZENET_CLIENTKEY as string;
//let apiLoginId = process.env.REACT_APP_AUTHORIZENET_LOGINID as string;

const clientKey = "8896XXXXXXXXXXXX";
const apiLoginId = "675XXXXXXX";

Then I get the "User authentication failed due to invalid authentication values" error.

Finally, if I copy the creds from the .env file in react-authorize.net I don't get console error/message, I get app screen that says:
Failed to process payment.

Any guidance would be greatly appreciated

**Comment by darkengine** [comment]
It seems you use TransactionKey as ClientKey here. The client key is way longer than this in our case.

**Comment by j-em** [comment]
If you tried what @darkengine proposed and it's still not working, feel free to reopen the issue.
