### ISSUE TITLE
allow custom styling

### ISSUE THREAD

**Issue by bgberk** [j-em/react-authorize-net#6]
I notice there's an exposed className prop in the FormComponent, but I'm not able to read the Typescript enough to understand how it all works. Is there a way to drop in custom styles? I tried overriding the class names generated by Styled Components, but the buildpack I'm using defaults to the old style.

**Comment by j-em** [comment]
Hi,

FormComponent is exposing a className prop that is applied to the top-most React element returned by the component.

Depending on what custom styles you are trying to apply exactly - this might or might not be doing what you are looking for.

The original idea when I first started this library was to provide all the plumbing necessary to integrate Authorize.Net in a React app in the form of a component using the "render prop" pattern (with FormContainer).

This means you can implement *any* UI for your forms by passing any components / functions returning React elements to the `component` prop of FormContainer.

FormComponent is just one example of what a component doing that might look like.

With that being said, I see in your fork that a lot of your custom styling requirements are about customizing the default font used by FormComponent and all its child elements.

Starting with that commit https://github.com/j-em/react-authorize-net/commit/058bb57f7bb5b18d6ca7dcfead2f1ff78fe5b3cb, all the child elements returned by FormComponent should inherit the font-family rule set for FormComponent itself.

This means you should be able to customize the font used in FormComponent (and all its child elements) by providing a className prop yourself that sets the font-family to what you want *or* by applying your custom styles directly by wrapping the component with `styled` before using it.
```js
const CustomForm = styled(FormComponent)`
font-family: Cutive
`
```
Does that help with what you are trying to achieve?
Don't hesitate to let me know if there is anything else.

**Comment by bgberk** [comment]
Thanks for the response!

I'm trying to use your FormComponent because its functionality is so robust. I started building a custom one, but it's difficult to hook into FormContainer. 

I'm using NextJS with Styled JSX, so I created a new component with a className:
`const StyledFormComponent = (props) => (
		<FormComponent className="styledForm" {...props}/>
	)`
and added a global style object with the following CSS: 
`.styledForm {
	font-family: "Cutive Mono";
	background-color: white;
	color: black;
}`

The only attribute that applied is the background-color, and only to the first div. I'm almost able to get what I want with selectors like `.styledForm button {}`, but because of the way the inputs are built, I can't target their containing divs. I'm not sure why the font-family attribute isn't being inherited correctly.

I think an ideal solution would be to pass a style object as a prop to FormComponent, which would then use that object to build its FormInput, PayButton, and Error components. Something like:
const styleObject = {
    form: {
        display: flex,
        flexDirection: column
    },
    button: {
        fontFamily: serif
    },
    input: {
        borderRadius: 0,
        border: 1px solid black;
    }
} 
`const StyledFormComponent = (props) => <FormComponent styles={styleObject} {...props} />`
Would that make sense? Or would it be easier for me to figure out how to build my own FormComponent and hook it into FormContainer's validation/props/etc?

**Comment by j-em** [comment]
Okay so as of v.0.3.0, you should now be able to apply custom styles to FormComponent and its rendered elements by using the `style` prop on it.

The `style` prop expect an object of this shape: 
```typescript
  style?: {
    form?: React.CSSProperties
    button?: React.CSSProperties
    input?: React.CSSProperties
  }
```

I added some stories in the project Storybook showcasing how you can customize the styling of FormComponent as well: https://github.com/j-em/react-authorize-net/blob/master/stories/index.tsx#L35

v0.3.0 should be currently live on npm as well.

Don't hesitate to let me know how this ends up working out for your use case.

Thanks again for the feedback - I really appreciate it!

**Comment by bgberk** [comment]
This works great and makes things a lot more flexible while retaining core functionality, thanks! One minor fix: 
lines 153/154: `color="white"` -> `color="inherit"`

To access pseudo-selectors, you can still pass a className to FormComponent and target elements (`.styledForm button:hover`). As far as I can tell, though, there's no way with React's inline styling to add a conditional style based on the valid prop. For my use, it's working much better than the hack I used before, and I'm happy to have this issue closed if you are!

**Comment by j-em** [comment]
Awesome!

Latest version on npm (v0.3.1) fixes the color props.

Don't hesitate to open another issue if there is anything else.
