### ISSUE TITLE
Webpack issues?

### ISSUE THREAD

**Issue by mikestecker** [j-em/react-authorize-net#7]
Apologies if this is a newbie question but I'm new to react so maybe I don't have something configured correctly, but I'm having trouble getting this component to load properly. I'm currently running React 16.9.0 and NextJS 9.0.3 and the component loads fine if I navigate to the page where the component is, but if I'm already on that page and I click refresh in my browser, I have Webpack errors:

```
SyntaxError: Unexpected identifier
Module._compile
internal/modules/cjs/loader.js:703:23
Module._extensions..js
internal/modules/cjs/loader.js:770:10
Module.load
internal/modules/cjs/loader.js:628:32
Function.Module._load
internal/modules/cjs/loader.js:555:12

Module.require
internal/modules/cjs/loader.js:666:19
require
internal/modules/cjs/helpers.js:16:16
react-authorize-net
webpack:/external "react-authorize-net":1

__webpack_require__
./webpack/bootstrap:21

... (and so forth)
```

I'm not having this problem anywhere else on the site. Is this something possibly with my Webpack config with NextJS?

**Comment by j-em** [comment]
Hello!

Thank you for reporting this.

After doing some investigating, this seems related to how Next.js handles third-party packages that are not exposed as CommonJS modules.

Since react-authorize-net is currently exposed only as an ES Module, you could use this plugin https://github.com/martpie/next-transpile-modules to easily transpile react-authorize-net everytime your Next.js app is rebuilt.

I tested the plugin on a fresh Next.js project with react-authorize-net imported and it seems to be fixing the issue.

Don't hesitate to let me know if you are still having trouble.

**Comment by mikestecker** [comment]
@j-em Thanks for the reply! I think that did it. I haven't fully clicked through all the pages yet but so far so good. Here's my `next.config.js` in case it helps anyone else:

```js
/* eslint-disable */
const withPlugins = require("next-compose-plugins");
const webpack = require("webpack");
const withCss = require("@zeit/next-css");
const withTM = require("next-transpile-modules");
const { parsed: localEnv } = require("dotenv").config();

module.exports = withPlugins(
  [
    [
      withCss,
      {
        webpack(config) {
          config.node = {
            net: "empty",
            tls: "empty",
            fs: "empty"
          };
          config.module.rules.push({
            test: /\.(png|svg|eot|otf|ttf|woff|woff2)$/,
            use: {
              loader: "url-loader",
              options: {
                limit: 8192,
                publicPath: "/_next/static/",
                outputPath: "static/",
                name: "[name].[ext]"
              }
            }
          });
          config.plugins.push(new webpack.EnvironmentPlugin(localEnv));
          return config;
        }
      }
    ],
    [
      withTM,
      {
        transpileModules: ["react-authorize-net"]
      }
    ]
  ],
  {
    // ...
  }
);
```

**Comment by j-em** [comment]
Glad to hear it, don't hesitate to open another issue if there is anything else.
