### ISSUE TITLE
Custom Payment Form submission trigger.

### ISSUE THREAD

**Issue by annshress** [j-em/react-authorize-net#9]
Can we remove the default FormComponent button, and trigger the card submission ourselves?

In our case, `Payment` form is a part of another form, and Pay button is triggering the form submission. Or do I need to create a custom payment form for this?

**Comment by j-em** [comment]
Hello!

The initial idea was that if you need custom behavior like this, you can trigger the submission by passing a custom view to `FormContainer` and call the `handleSubmit` handler yourself wherever you want.

With that being said, I'm totally open to suggestions (or PRs) that would help with a use case like yours. 

Thanks!

**Comment by j-em** [comment]
Closing, feel free to open a new issue if there is anything else!
